version: '3'

volumes: 
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/production'
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
      - 'DATABASE_PASSWORD=postgres'
# ↓-itを表す
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:9.5.18
    volumes: 
     - 'db-data:/var/lib/postgresql/data'
